spring:
  application:
    name: TruckerFM dev
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3309/data}"
    username: root
    password: "${SPRING_DATASOURCE_PASSWORD:password}"
  flyway:
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code # needs manual session invalidation on logout, check refresh_token
            scope: openid
#            redirect-uri: "http://localhost:8081/app"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak

# to allow swagger-ui to perform requests against HTTPS
server:
  forward-headers-strategy: framework
  port: 8081
logging:
  level:
    org.springframework.web: TRACE
