spring:
  application:
    name: "Shut Up And Charge"
  datasource:
    url: "${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/charging?stringtype=unspecified}"
    username: charging-user
    password: "${POSTGRES_DB_PASSWORD:charging-password}"
    driver-class-name: org.postgresql.Driver
  flyway:
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: "YOUR_VALUE"
            client-secret: "YOUR_VALUE"
            client-authentication-method: "client_secret_post"
            scope:
              - openid
              - profile
              - email
              - roles
            authorization-grant-type: authorization_code # needs manual session invalidation on logout, check refresh_token
        provider:
          keycloak:
            issuer-uri: "https://sso.momosi.org/realms/momosi"

# to allow swagger-ui to perform requests against HTTPS
server:
  forward-headers-strategy: framework
