version: '3.7'

services:

  charging-database:
    image: postgres:latest
    container_name: charging-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: charging
      POSTGRES_USER: charging-user
      POSTGRES_PASSWORD: charging-password
