version: '3.3'

services:

  trucker-database:
    image: mysql:8.1.0
    container_name: trucker-database
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: 'data'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  keycloak:
    image: keycloak/keycloak:23.0.7
    container_name: keycloak
    ports:
      - '8080:8080'
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'password'
    command: start-dev
